### Create new user
POST http://localhost:5000/auth/signup
Content-Type: application/json

{
  "email": "ahmed@gmail.com",
  "password": "123456"
}

###Get user by id
GET http://localhost:5000/auth/20
Content-Type: application/json

{}

###Get All users with the same email
GET http://localhost:5000/auth?email=ahmed@gmail.com
Content-Type: application/json

{}

### update user
PATCH  http://localhost:5000/auth/20
Content-Type: application/json

{
  "email": "dada@gmail.com",
  "password": "123"
}


### delete user
DELETE http://localhost:5000/auth/4
Content-Type: application/json

{}