### Create new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "test2@test.com",
  "password": "123456"
}

### Sign in
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "123456"
}

### Sing Out
POST  http://localhost:3000/auth/signout
Content-Type: application/json

{}

### Get Current User
GET http://localhost:3000/auth/whoAmI
Content-Type: application/json

{}


###Get user by id
GET http://localhost:3000/auth/1
Content-Type: application/json

{}

###Get All users with the same email
GET http://localhost:3000/auth?email=ahmed@gmail.com
Content-Type: application/json

{}

### update user
PATCH  http://localhost:3000/auth/12
Content-Type: application/json

{
  "email": "dada@gmail.com"
}


### delete user
DELETE http://localhost:3000/auth/4
Content-Type: application/json

{}


### Set color
GET http://localhost:3000/auth/colors/red
Content-Type: application/json

{}

### Get color
GET http://localhost:3000/auth/colors
Content-Type: application/json

{}